name: Deploy to github pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: manoelcampos/asciidoctor-ghpages-action@v2
